dist: xenial
sudo: required
language: groovy
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
matrix:
  allow_failures:
    jdk: openjdk11
  fast_finish: true
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install graphviz
  - sudo pip install awscli
install:
  - sudo apt-get install -y realpath
git:
  submodules: true
env:
  global:
    - GRADLE_OPTS='-Dorg.gradle.daemon=false'
    - TEST_JDK=
before_script:
  - rm $HOME/.gitconfig
  - mkdir -p "$HOME/.nextflow" && echo "providers.github.auth='$NXF_GITHUB_ACCESS_TOKEN'" > "$HOME/.nextflow/scm"
  - make assemble
script:
  - |
    set -e;
    make test install;
    ./integration-tests.sh
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash pub-tests.sh travis; fi
